from django.db import models
from django.utils import timezone

# Create your models here.
class Players(models.Model):
    _id = models.CharField(primary_key=True,null=False,max_length=15)
    date = models.DateTimeField(default=timezone.datetime.now())
    email = models.CharField(null=False,max_length=64)
    xp = models.IntegerField(null=False)
    coin = models.IntegerField(null=True)
    image = models.ImageField(null=True,upload_to='images/')
    name = models.CharField(null=True,max_length=64)
    playing = models.IntegerField(default=1)
    country = models.CharField(null=False,max_length=15)
    dimond = models.IntegerField(null=True)
    #5_spell
    shield_spell = models.IntegerField(null=True)
    slo_mo_spell= models.IntegerField(null=True)
    productive_spell = models.IntegerField(null=True)
    momentum_spell = models.IntegerField(null=True)
    healing_spell = models.IntegerField(null=True)
    #fruits_skins
    one_scene_un = models.IntegerField(null=True)
    two_scene_un = models.IntegerField(null=True)
    three_scene_un = models.IntegerField(null=True)
    four_scene_un = models.IntegerField(null=True)
    five_scene_un = models.IntegerField(null=True)
    six_scene_un = models.IntegerField(null=True)
    seven_scene_un= models.IntegerField(null=True)
    eight_scene_un = models.IntegerField(null=True)
    nine_scene_un = models.IntegerField(null=True)
    ten_scene_un = models.IntegerField(null=True)
    one_fruits_un = models.IntegerField(null=True)
    two_fruits_un = models.IntegerField(null=True)
    three_fruits_un = models.IntegerField(null=True)
    four_fruits_un = models.IntegerField(null=True)
    five_fruits_un = models.IntegerField(null=True)
    six_fruits_un = models.IntegerField(null=True)
    seven_fruits_un = models.IntegerField(null=True)
    eight_fruits_un = models.IntegerField(null=True)
    nine_fruits_un = models.IntegerField(null=True)
    ten_fruits_un = models.IntegerField(null=True)
    eleven_fruits_un = models.IntegerField(null=True)
    twelve_fruits_un = models.IntegerField(null=True)
    thirteen_fruits_un = models.IntegerField(null=True)
    fourteen_fruits_un = models.IntegerField(null=True)
    fifteen_fruits_un = models.IntegerField(null=True)
    sixteen_fruits_un = models.IntegerField(null=True)
    seventeen_fruits_un = models.IntegerField(null=True)
    eighteen_fruits_un = models.IntegerField(null=True)
    nineteen_fruits_un = models.IntegerField(null=True)
    twenty_fruits_un = models.IntegerField(null=True)
    twentyone_fruits_un = models.IntegerField(null=True)
    twentytwo_fruits_un = models.IntegerField(null=True)
    twentythree_fruits_un = models.IntegerField(null=True)
    twentyfour_fruits_un = models.IntegerField(null=True)
    twentyfive_fruits_un = models.IntegerField(null=True)


    def __str__(self):
        return self._id
