# Generated by Django 2.2.7 on 2019-11-10 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 10, 21, 51, 53, 555480))),
                ('expair', models.DateTimeField(blank=True, null=True)),
                ('shield_spell_u', models.IntegerField(null=True)),
                ('slo_mo_spell_u', models.IntegerField(null=True)),
                ('productive_spell_u', models.IntegerField(null=True)),
                ('momentum_spell_u', models.IntegerField(null=True)),
                ('healing_spell_u', models.IntegerField(null=True)),
                ('one_scene_u', models.IntegerField(null=True)),
                ('two_scene_u', models.IntegerField(null=True)),
                ('three_scene_u', models.IntegerField(null=True)),
                ('four_scene_u', models.IntegerField(null=True)),
                ('five_scene_u', models.IntegerField(null=True)),
                ('six_scene_u', models.IntegerField(null=True)),
                ('seven_scene_u', models.IntegerField(null=True)),
                ('eight_scene_u', models.IntegerField(null=True)),
                ('nine_scene_u', models.IntegerField(null=True)),
                ('ten_scene_u', models.IntegerField(null=True)),
                ('one_fruits_u', models.IntegerField(null=True)),
                ('two_fruits_u', models.IntegerField(null=True)),
                ('three_fruits_u', models.IntegerField(null=True)),
                ('four_fruits_u', models.IntegerField(null=True)),
                ('five_fruits_u', models.IntegerField(null=True)),
                ('six_fruits_u', models.IntegerField(null=True)),
                ('seven_fruits_u', models.IntegerField(null=True)),
                ('eight_fruits_u', models.IntegerField(null=True)),
                ('nine_fruits_u', models.IntegerField(null=True)),
                ('ten_fruits_u', models.IntegerField(null=True)),
                ('eleven_fruits_u', models.IntegerField(null=True)),
                ('twelve_fruits_u', models.IntegerField(null=True)),
                ('thirteen_fruits_u', models.IntegerField(null=True)),
                ('fourteen_fruits_u', models.IntegerField(null=True)),
                ('fifteen_fruits_u', models.IntegerField(null=True)),
                ('sixteen_fruits_u', models.IntegerField(null=True)),
                ('seventeen_fruits_u', models.IntegerField(null=True)),
                ('eighteen_fruits_u', models.IntegerField(null=True)),
                ('nineteen_fruits_u', models.IntegerField(null=True)),
                ('twenty_fruits_u', models.IntegerField(null=True)),
                ('twentyone_fruits_u', models.IntegerField(null=True)),
                ('twentytwo_fruits_u', models.IntegerField(null=True)),
                ('twentythree_fruits_u', models.IntegerField(null=True)),
                ('twentyfour_fruits_u', models.IntegerField(null=True)),
                ('twentyfive_fruits_u', models.IntegerField(null=True)),
                ('dead', models.IntegerField(null=True)),
                ('total_fruits', models.IntegerField(null=True)),
                ('fblogin', models.CharField(default='deactive', max_length=10)),
                ('_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Players')),
            ],
        ),
    ]
