# Generated by Django 2.2.7 on 2019-11-09 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 2, 53, 22, 864121)),
        ),
    ]
