# Generated by Django 2.2.7 on 2019-11-10 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 10, 21, 51, 53, 494461))),
                ('email', models.CharField(max_length=64)),
                ('xp', models.IntegerField()),
                ('coin', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('name', models.CharField(max_length=64, null=True)),
                ('playing', models.IntegerField(default=1)),
                ('country', models.CharField(max_length=15)),
                ('dimond', models.IntegerField(null=True)),
                ('shield_spell', models.IntegerField(null=True)),
                ('slo_mo_spell', models.IntegerField(null=True)),
                ('productive_spell', models.IntegerField(null=True)),
                ('momentum_spell', models.IntegerField(null=True)),
                ('healing_spell', models.IntegerField(null=True)),
                ('one_scene_un', models.IntegerField(null=True)),
                ('two_scene_un', models.IntegerField(null=True)),
                ('three_scene_un', models.IntegerField(null=True)),
                ('four_scene_un', models.IntegerField(null=True)),
                ('five_scene_un', models.IntegerField(null=True)),
                ('six_scene_un', models.IntegerField(null=True)),
                ('seven_scene_un', models.IntegerField(null=True)),
                ('eight_scene_un', models.IntegerField(null=True)),
                ('nine_scene_un', models.IntegerField(null=True)),
                ('ten_scene_un', models.IntegerField(null=True)),
                ('one_fruits_un', models.IntegerField(null=True)),
                ('two_fruits_un', models.IntegerField(null=True)),
                ('three_fruits_un', models.IntegerField(null=True)),
                ('four_fruits_un', models.IntegerField(null=True)),
                ('five_fruits_un', models.IntegerField(null=True)),
                ('six_fruits_un', models.IntegerField(null=True)),
                ('seven_fruits_un', models.IntegerField(null=True)),
                ('eight_fruits_un', models.IntegerField(null=True)),
                ('nine_fruits_un', models.IntegerField(null=True)),
                ('ten_fruits_un', models.IntegerField(null=True)),
                ('eleven_fruits_un', models.IntegerField(null=True)),
                ('twelve_fruits_un', models.IntegerField(null=True)),
                ('thirteen_fruits_un', models.IntegerField(null=True)),
                ('fourteen_fruits_un', models.IntegerField(null=True)),
                ('fifteen_fruits_un', models.IntegerField(null=True)),
                ('sixteen_fruits_un', models.IntegerField(null=True)),
                ('seventeen_fruits_un', models.IntegerField(null=True)),
                ('eighteen_fruits_un', models.IntegerField(null=True)),
                ('nineteen_fruits_un', models.IntegerField(null=True)),
                ('twenty_fruits_un', models.IntegerField(null=True)),
                ('twentyone_fruits_un', models.IntegerField(null=True)),
                ('twentytwo_fruits_un', models.IntegerField(null=True)),
                ('twentythree_fruits_un', models.IntegerField(null=True)),
                ('twentyfour_fruits_un', models.IntegerField(null=True)),
                ('twentyfive_fruits_un', models.IntegerField(null=True)),
            ],
        ),
    ]
